name: deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Auth with credentials
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_UPLOAD_BUCKET_CRED }}

      - name: Configure Docker
        run: gcloud auth configure-docker us-east4-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
            docker build -t us-east4-docker.pkg.dev/wide-strength-418218/backend/my-image .
            docker push us-east4-docker.pkg.dev/wide-strength-418218/backend/my-image
